### ISSUE TITLE
Packets not present in the path

### ISSUE THREAD

**Issue by Systemac** [CiscoCXSecurity/enum4linux#18]
I tried to use the utility but I get this error.

I tried to reinstall smbclient but still the same error, here is my PATH too: 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
 I'm under Kali linux 2021.

@kali:/$ enum4linux 10.10.163.75
ERROR: nmblookup is not in your path.  Check that samba package is installed
ERROR: net is not in your path.  Check that samba package is installed
ERROR: rpcclient is not in your path.  Check that samba package is installed
ERROR: smbclient is not in your path.  Check that samba package is installed
WARNING: polenum is not in your path.  Check that package is installed and your PATH is sane.
WARNING: ldapsearch is not in your path.  Check that package is installed and your PATH is sane.
For Gentoo, you need to install the "samba" package
For Debian, you need to install the "smbclient" package

**Comment by PhForty** [comment]
Hey,
I came across the same output recently in a different context, maybe it'll put someone else on the right track:
I was using enum4linux through proxychains (which is relatively verbose). It failed with the same error message as above but I was sure that my PATH is correct because I made the script be more verbose about its perspective on results of `which $prog`

My assumption: The verbose output of proxychains mingled with the regex which enum4linux uses to check whether the `which $prog` succeeds.
My quickfix: Use proxychains with the -q flag to suppress its output.

**Comment by M-Davies** [comment]
I've just come across this in the same context as the original:
```
$ sudo proxychains enum4linux -a -l <ip-address>
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
ERROR: nmblookup is not in your path.  Check that samba package is installed
ERROR: net is not in your path.  Check that samba package is installed
ERROR: rpcclient is not in your path.  Check that samba package is installed
ERROR: smbclient is not in your path.  Check that samba package is installed
WARNING: polenum is not in your path.  Check that package is installed and your PATH is sane.
WARNING: ldapsearch is not in your path.  Check that package is installed and your PATH is sane.
For Gentoo, you need to install the "samba" package
For Debian, you need to install the "smbclient" package
```

**Comment by ZackInMA** [comment]
Issue has been open for a year+. If it hasn't been fixed by now, safe to say it's prob not going to be.

**Comment by parchaks** [comment]
I recently ran into this issue. The error arises from the script attempting to use 'which' for the dependency check. If 'which' is not available either by not being on the path or not installed, it will default to saying the samba tools are not installed.

**Comment by jlanguell** [comment]
> Hey, I came across the same output recently in a different context, maybe it'll put someone else on the right track: I was using enum4linux through proxychains (which is relatively verbose). It failed with the same error message as above but I was sure that my PATH is correct because I made the script be more verbose about its perspective on results of `which $prog`
> 
> My assumption: The verbose output of proxychains mingled with the regex which enum4linux uses to check whether the `which $prog` succeeds. My quickfix: Use proxychains with the -q flag to suppress its output.

Quick lifesaver -- Thanks @M-Davies !

**Comment by M-Davies** [comment]
That was @PhForty but you're welcome I guess :)

**Comment by ilyas-Essar** [comment]
@PhForty thanks dude you saved my day.

**Comment by 0xCZR1** [comment]
> Hey, I came across the same output recently in a different context, maybe it'll put someone else on the right track: I was using enum4linux through proxychains (which is relatively verbose). It failed with the same error message as above but I was sure that my PATH is correct because I made the script be more verbose about its perspective on results of `which $prog`
> 
> My assumption: The verbose output of proxychains mingled with the regex which enum4linux uses to check whether the `which $prog` succeeds. My quickfix: Use proxychains with the -q flag to suppress its output.

The definition of 2000IQ!
